# 재생목록 ID로 재생목록 항목 가져오기
query GetPlaylistItems {
  getPlaylistItems(
    part: "snippet,contentDetails"
    playlistId: "PL7jH19IHhOLNiUmS1s_4gKfWU43r8c-0p"
    maxResults: 50
  ) {
    items {
      id
      snippet {
        title
        description
        thumbnails {
          default {
            url
          }
        }
        position
        resourceId {
          videoId
        }
      }
      contentDetails {
        videoId
        videoPublishedAt
      }
    }
    pageInfo {
      totalResults
      resultsPerPage
    }
    nextPageToken
  }
}

# 특정 재생목록 항목 ID로 정보 가져오기
query GetPlaylistItemById {
  getPlaylistItems(
    part: "snippet,status"
    id: "UEw3akgxOUlIaE9MTmlVbVMxc180Z0tmV1U0M3I4Yy0wcC4yODlGNEE0NkRGMEEzMEQy"
  ) {
    items {
      id
      snippet {
        title
        description
        playlistId
        position
        resourceId {
          videoId
        }
      }
      status {
        privacyStatus
      }
    }
  }
}

# 재생목록에서 특정 동영상 ID로 항목 찾기
query GetPlaylistItemByVideoId {
  getPlaylistItems(
    part: "snippet,contentDetails"
    playlistId: "PL7jH19IHhOLNiUmS1s_4gKfWU43r8c-0p"
    videoId: "Jm5v-dZnYCs"
  ) {
    items {
      snippet {
        title
        position
      }
      contentDetails {
        videoId
        startAt
        endAt
      }
    }
  }
}